# src/skin_list.py

"""
Zmieniliśmy strukturę na SŁOWNIK (dictionary).
Klucz to "Typ Broni" (np. "AK-47").
Wartość to LISTA skinów dla tej broni (np. ["Redline", "Asiimov"]).

Dla skrzynek, wartość to pusta lista [].
"""

SKIN_DATA = {
    # --- Karbany ---
   "AK-47": [
        "Aquamarine Revenge",
        "Asiimov",
        "Baroque Purple",
        "B the Monster",
        "Black Laminate",
        "Bloodsport",
        "Blue Laminate",
        "Cartel",
        "Case Hardened",
        "Elite Build",
        "Emerald Pinstripe",
        "Fire Serpent",
        "First Class",
        "Frontside Misty",
        "Fuel Injector",
        "Gold Arabesque",
        "Green Laminate",
        "Head Shot",
        "Hydroponic",
        "Ice Coaled",
        "Inheritance",
        "Jaguar",
        "Jet Set",
        "Jungle Spray",
        "Leet Museo",
        "Legion of Anubis",
        "Neon Rider",
        "Neon Revolution",
        "Nightwish",
        "Nouveau Rouge",
        "Orbit Mk01",
        "Panthera onca",
        "Phantom Disruptor",
        "Point Disarray",
        "Predator",
        "Rat Rod",
        "Red Laminate",
        "Redline",
        "Safari Mesh",
        "Slate",
        "Steel Delta",
        "The Empress",
        "The Oligarch",
        "Uncharted",
        "Vulcan",
        "Wasteland Rebel",
        "Wild Lotus",
        "Wintergreen",
        "X-Ray"
    ],
    "M4A4": [
        "Asiimov",
        "Bullet Rain",
        "Buzz Kill",
        "Choppa",
        "Converter",
        "Cyber Security",
        "Dark Blossom",
        "Daybreak",
        "Desert Storm",
        "Desert-Strike",
        "Desolate Space",
        "Etch Lord",
        "Evil Daimyo",
        "Eye of Horus",
        "Faded Zebra",
        "Full Throttle",
        "Global Offensive",
        "Griffin",
        "Hellfire",
        "Hellish",
        "Howl",
        "In Living Color",
        "Jungle Tiger",
        "Magnesium",
        "Mainframe",
        "Modern Hunter",
        "Naval Shred Camo",
        "Neo-Noir",
        "Poly Mag",
        "Polysoup",
        "Poseidon",
        "Radiation Hazard",
        "Red DDPAT",
        "Royal Paladin",
        "Sheet Lightning",
        "Spider Lily",
        "Steel Work",
        "Temukau",
        "The Battlestar",
        "The Coalition",
        "The Emperor",
        "Tooth Fairy",
        "Tornado",
        "Turbine",
        "Urban DDPAT",
        "X-Ray",
        "Zirka",
        "龍王 (Dragon King)"
    ],
   "M4A1-S": [
        "Atomic Alloy",
        "Basilisk",
        "Black Lotus",
        "Blood Tiger",
        "Blue Phosphor",
        "Boreal Forest",
        "Briefing",
        "Bright Water",
        "Chantico's Fire",
        "Control Panel",
        "Cyrex",
        "Dark Water",
        "Decimator",
        "Emphorosaur-S",
        "Fade",
        "Fizzy POP",
        "Flashback",
        "Glitched Paint",
        "Golden Coil",
        "Guardian",
        "Hot Rod",
        "Hyper Beast",
        "Icarus Fell",
        "Imminent Danger",
        "Knight",
        "Leaded Glass",
        "Liquidation",
        "Master Piece",
        "Mecha Industries",
        "Moss Quartz",
        "Mud-Spec",
        "Night Terror",
        "Nightmare",
        "Nitro",
        "Player Two",
        "Printstream",
        "Rose Hex",
        "Solitude",
        "Stratosphere",
        "Vaporwave",
        "VariCamo",
        "Wash me plz",
        "Welcome to the Jungle"
    ],
    "AWP": [
        "Acheron",
        "Arsenic Spill",
        "Asiimov",
        "Atheris",
        "Black Nile",
        "BOOM",
        "Capillary",
        "Chrome Cannon",
        "Chromatic Aberration",
        "CMYK",
        "Containment Breach",
        "Corticera",
        "Crakow!",
        "Desert Hydra",
        "Dragon Lore",
        "Duality",
        "Electric Hive",
        "Elite Build",
        "Exoskeleton",
        "Fade",
        "Fever Dream",
        "Graphite",
        "Green Energy",
        "Gungnir",
        "Hyper Beast",
        "Ice Coaled",
        "Lightning Strike",
        "LongDog",
        "Man-o'-war",
        "Medusa",
        "Mortis",
        "Neo-Noir",
        "Oni Taiji",
        "PAW",
        "Phobos",
        "Pink DDPAT",
        "Pit Viper",
        "POP AWP",
        "Printstream",
        "Redline",
        "Safari Mesh",
        "Silk Tiger",
        "Snake Camo",
        "Sun in Leo",
        "The Prince",
        "Wildfire",
        "Worm God"
    ],
    "FAMAS": [
        "Afterimage",
        "Bad Trip",
        "CaliCamo",
        "Colony",
        "Commemoration",
        "Contrast Spray",
        "Crypsis",
        "Cyanospatter",
        "Dark Water",
        "Decommissioned",
        "Djinn",
        "Doomkitty",
        "Eye of Athena",
        "Faulty Wiring",
        "Hexane",
        "Macabre",
        "Mecha Industries",
        "Meltdown",
        "Meow 36",
        "Neural Net",
        "Night Borre",
        "Prime Conspiracy",
        "Pulse",
        "Rapid Eye Movement",
        "Roll Cage",
        "Sergeant",
        "Spitfire",
        "Styx",
        "Sundown",
        "Survivor Z",
        "Teardown",
        "Valence",
        "Waters of Nephthys",
        "ZX Spectron"
    ],
   "Galil AR": [
        "Acid Dart",
        "Akoben",
        "Amber Fade",
        "Aqua Terrace",
        "Black Sand",
        "Blue Titanium",
        "CAUTION!",
        "Cerberus",
        "Chatterbox",
        "Chromatic Aberration",
        "Cold Fusion",
        "Connexion",
        "Control",
        "Crimson Tsunami",
        "Destroyer",
        "Dusk Ruins",
        "Eco",
        "Firefight",
        "Green Apple",
        "Grey Smoke",
        "Hunting Blind",
        "Kami",
        "Metallic Squeezer",
        "NV",
        "O-Ranger",
        "Orange DDPAT",
        "Phoenix Blacklight",
        "Rainbow Spoon",
        "Robin's Egg",
        "Rocket Pop",
        "Sage Spray",
        "Sandstorm",
        "Shattered",
        "Signal",
        "Stone Cold",
        "Sugar Rush",
        "Tornado",
        "Tuxedo",
        "Urban Rubble",
        "Vandal",
        "VariCamo",
        "Winter Forest"
    ],
    "AUG": [
        "Akihabara Accept",
        "Amber Fade",
        "Amber Slipstream",
        "Anodized Navy",
        "Arctic Wolf",
        "Aristocrat",
        "Bengal Tiger",
        "Carved Jade",
        "Chameleon",
        "Commando Company",
        "Condemned",
        "Contractor",
        "Copperhead",
        "Daedalus",
        "Death by Puppy",
        "Eye of Zapems",
        "Flame Jörmungandr",
        "Fleet Flock",
        "Hot Rod",
        "Lil' Pig",
        "Luxe Trim",
        "Midnight Lily",
        "Momentum",
        "Navy Murano",
        "Plague",
        "Radiation Hazard",
        "Random Access",
        "Ricochet",
        "Sand Storm",
        "Snake Pit",
        "Spalted Wood",
        "Steel Sentinel",
        "Stymphalian",
        "Storm",
        "Surveillance",
        "Sweeper",
        "Syd Mead",
        "Tom Cat",
        "Torque",
        "Trigger Discipline",
        "Triqua",
        "Wings"
    ],
    "G3SG1": [
        "Ancient Ritual",
        "Arctic Camo",
        "Arctic DDPAT",
        "Azure Zebra",
        "Black Sand",
        "Chronos",
        "Contractor",
        "Desert Storm",
        "Digital Mesh",
        "Dream-state",
        "Flux",
        "Green Apple",
        "High Seas",
        "Jungle",
        "Jungle Dashed",
        "Keeping Tabs",
        "Murky",
        "New-Roots",
        "Operator",
        "Orange Kimono",
        "Polar Camo",
        "Safari Mesh",
        "Scavenger",
        "Stinger",
        "The Executioner",
        "VariCamo",
        "Ventilator"
    ],
    "SCAR-20": [
        "Army Sheen",
        "Assault",
        "Bloodsport",
        "Blueprint",
        "Brass",
        "Caged",
        "Carbon Fiber",
        "Cardiac",
        "Contractor",
        "Crimson Web",
        "Cyrex",
        "Emerald",
        "Enforcer",
        "Fragments",
        "Green Marine",
        "Grotto",
        "Jungle Slipstream",
        "Magna Carta",
        "Outbreak",
        "Palm",
        "Poultrygeist",
        "Powercore",
        "Sand Mesh",
        "Splash Jam",
        "Stone Mosaico",
        "Storm",
        "Torn",
        "Trail Blazer"
    ],
    "SG 553": [
        "Aerial",
        "Aloha",
        "Anodized Navy",
        "Army Sheen",
        "Atlas",
        "Barricade",
        "Basket Halftone",
        "Berry Gel Coat",
        "Bleached",
        "Bulldozer",
        "Candy Apple",
        "Colony IV",
        "Cyberforce",
        "Cyrex",
        "Damascus Steel",
        "Danger Close",
        "Darkwing",
        "Desert Blossom",
        "Dragon Tech",
        "Fallout Warning",
        "Gator Mesh",
        "Hazard Pay",
        "Heavy Metal",
        "Hypnotic",
        "Integrale",
        "Lush Ruins",
        "Night Camo",
        "Ol' Rusty",
        "Phantom",
        "Pulse",
        "Tiger Moth",
        "Tornado",
        "Traveler",
        "Triarch",
        "Ultraviolet",
        "Wave Spray",
        "Waves Perforated"
    ],
    "SSG 08": [
        "Abyss",
        "Acid Fade",
        "Acheron",
        "Assault",
        "Azure Glyph",
        "Big Iron",
        "Blood in the Water",
        "Bloodshot",
        "Blue Spruce",
        "Blush Pour",
        "Carbon Fiber",
        "Dark Water",
        "Death Strike",
        "Death's Head",
        "Detour",
        "Dezastre",
        "Dragonfire",
        "Fever Dream",
        "Ghost Crusader",
        "Green Ceramic",
        "Grey Smoke",
        "Halftone Whorl",
        "Hand Brake",
        "Jungle Dashed",
        "Lichen Dashed",
        "Mainframe 001",
        "Mayan Dreams",
        "Memorial",
        "Necropos",
        "Orange Filigree",
        "Parallax",
        "Prey",
        "Rapid Transit",
        "Red Stone",
        "Sand Dune",
        "Sea Calico",
        "Slashed",
        "Spring Twilly",
        "Threat Detected",
        "Tiger Tear",
        "Tropical Storm",
        "Turbo Peek",
        "Zeno"
    ],

    # --- Pistolety ---
    "Desert Eagle": [
        "Blaze", "Printstream", "Fennec Fox", "Code Red", "Ocean Drive",
        "Sunset Storm 壱", "Sunset Storm 弐", "Conspiracy", "Mecha Industries"
    ],
    "USP-S": [
        "Kill Confirmed", "The Traitor", "Printstream", "Neo-Noir", "Orion",
        "Cortex", "Dark Water", "Target Acquired"
    ],
    "Glock-18": [
        "Fade", "Gamma Doppler", "Twilight Galaxy", "Water Elemental", "Neo-Noir",
        "Vogue", "Bullet Queen", "Snack Attack"
    ],
    "Five-SeveN": [
        "Case Hardened", "Hyper Beast", "Monkey Business", "Angry Mob", "Fowl Play", "Boost Protocol"
    ],
    "Tec-9": [
        "Fuel Injector", "Nuclear Threat", "Isaac", "Bamboozle", "Remote Control"
    ],
    "CZ75-Auto": [
    "Arctic Camo",
    "Army Sheen",
    "Carbon Fiber",
    "Chalice",
    "Circaetus",
    "Crimson Web",
    "Dark Water",
    "Distressed",
    "Eco",
    "Emerald",
    "Emerald Quartz",
    "Fuchsia Is Shock",
    "Green Plaid",
    "Hexane",
    "Imprint",
    "Indigo",
    "Jungle Dashed",
    "Midnight Palm",
    "Nitro",
    "Orange Peel",
    "Poison Dart",
    "Pole Position",
    "Polymer",
    "Precision",
    "Red Astor",
    "Silver",
    "Silver Decor",
    "Snakeskin",
    "Syndicate",
    "Tacticat",
    "The Fuschia Is Now",
    "Tigris",
    "Tread Plate",
    "Tread",
    "Tuxedo",
    "Twist",
    "Vendetta",
    "Victoria",
    "Violet Modular",
    "Walnut",
    "Xiangliu",
    "Yellow Jacket"
],
"P2000": [
    "Acid Etched",
    "Amber Fade",
    "Chainmail",
    "Coach Class",
    "Code Red",
    "Corticera",
    "Cream",
    "Dispatch",
    "Emerald Dragon",
    "Fire Elemental",
    "Gnarled",
    "Granite Marbleized",
    "Grassland",
    "Grassland Leaves",
    "Handgun",
    "Imperial",
    "Imperial Dragon",
    "Ivory",
    "Lifted Spirits",
    "Obsidian",
    "Ocean Foam",
    "Oceanic",
    "Panther Camo",
    "Pathfinder",
    "Pistolero",
    "Red FragCam",
    "Scorpion",
    "Silver",
    "Space Race",
    "Summer Garden",
    "Turf",
    "Urban Hazard",
    "Urban Perforated",
    "Wicked Sick",
    "Woodsman",
    "X-Ray"
],"Dual Berettas": [
        "Angel Eyes",
        "Anodized Navy",
        "Balance",
        "Black Limba",
        "BorDeux",
        "Briar",
        "Cartel",
        "Cobra Strike",
        "Cobalt Quartz",
        "Colony",
        "Contractor",
        "Demolition",
        "Dezastre",
        "Drift Wood",
        "Duelist",
        "Dualing Dragons",
        "Elite 1.6",
        "Emerald",
        "Flora Carnivora",
        "Heist",
        "Hemoglobin",
        "Hideout",
        "Hydro Strike",
        "Marina",
        "Melondrama",
        "Moon in Libra",
        "Oil Change",
        "Panther",
        "Polished Malachite",
        "Pyre",
        "Retribution",
        "Rose Nacre",
        "Royal Consorts",
        "Shred",
        "Stained",
        "Sweet Little Angels",
        "Switch Board",
        "Tread",
        "Twin Turbo",
        "Urban Shock",
        "Ventilators"
    ],
    "P250": [
    "Acanthus",
    "Adaptation",
    "Affected",
    "Apep's Curse",
    "Asiimov",
    "Bengal Tiger",
    "Black & Tan",
    "Bone Mask",
    "Boreal Forest",
    "Cartel",
    "Cassette",
    "Contaminant",
    "Contrast Spray",
    "Crackle",
    "Crimson Kimono",
    "Dark Filigree",
    "Digital Architect",
    "Drought",
    "Dunes",
    "Exchanger",
    "Facets",
    "Forest Night",
    "Franklin",
    "Gunsmoke",
    "Inferno",
    "Iron Clad",
    "Mehndi",
    "Metallic DDPAT",
    "Mint Kimono",
    "Modern Hunter",
    "Muertos"],
    "R8 Revolver": [
    "Amber Fade",
    "Banana Cannon",
    "Blaze",
    "Bone Mask",
    "Bone Forged",
    "Canal Spray",
    "Comet",
    "Cool Mint",
    "Crazy 8",
    "Crimson Web",
    "Deadly Poison",
    "Desert Brush",
    "Fade",
    "Grip",
    "Groundwater",
    "Inlay",
    "Junkyard",
    "Junk Yard",
    "Llama Cannon",
    "Memento",
    "Mint Frappe",
    "Night",
    "Nitro",
    "Phoenix Marker",
    "Reboot",
    "Scavenger",
    "Skull Crusher",
    "Survivalist",
    "Uncharted",
    "Venom",
    "Weasel",
    "Zebra"
],


    # --- PM-y ---
    "MP9": [
        "Wild Lily", "Bulldozer", "Hot Rod", "Starlight Protector", "Food Chain"
    ],
    "MAC-10": [
        "Case Hardened", "Neon Rider", "Stalker", "Gold Brick", "Disco Tech"
    ],
    "MP5-SD": [
    "Acid Wash",
    "Agent",
    "Ammo Drop",
    "Autumn Twilly",
    "Bamboo Garden",
    "Blush",
    "Catacomb",
    "Condition Zero",
    "Containment Breach",
    "Co-Processor",
    "Desert Strike",
    "Dirt Drop",
    "Gauss",
    "Hybrid",
    "Kitbash",
    "Lab Rats",
    "Liquidation",
    "Necro Jr.",
    "Oxide Oasis",
    "Phosphor",
    "Shattered Web",
    "Spring Twilly",
    "Stacked",
    "Takeover",
    "Violet"
],
"Dual Berettas": [
        "Angel Eyes",
        "Anodized Navy",
        "Balance",
        "Black Limba",
        "BorDeux",
        "Briar",
        "Cartel",
        "Cobra Strike",
        "Cobalt Quartz",
        "Colony",
        "Contractor",
        "Demolition",
        "Dezastre",
        "Drift Wood",
        "Duelist",
        "Dualing Dragons",
        "Elite 1.6",
        "Emerald",
        "Flora Carnivora",
        "Heist",
        "Hemoglobin",
        "Hideout",
        "Hydro Strike",
        "Marina",
        "Melondrama",
        "Moon in Libra",
        "Oil Change",
        "Panther",
        "Polished Malachite",
        "Pyre",
        "Retribution",
        "Rose Nacre",
        "Royal Consorts",
        "Shred",
        "Stained",
        "Sweet Little Angels",
        "Switch Board",
        "Tread",
        "Twin Turbo",
        "Urban Shock",
        "Ventilators"
    ],
    "PP-Bizon": [
        "Antique",
        "Bamboo Print",
        "Balance",
        "Blue Streak",
        "BorDeux",
        "Brass",
        "Breaker Box",
        "Candy Apple",
        "Carbon Fiber",
        "Chemical Green",
        "Cobalt Halftone",
        "Colony",
        "Contractor",
        "Death Rattle",
        "Demolition",
        "Drift Wood",
        "Duelist",
        "Elite 1.6",
        "Embargo",
        "Emerald",
        "Forest Leaves",
        "Fuel Rod",
        "Harvester",
        "Heist",
        "High Roller",
        "Hydro Strike",
        "Irradiated Alert",
        "Judgement of Anubis",
        "Jungle Slipstream",
        "Lumen",
        "Marina",
        "Melondrama",
        "Modern Hunter",
        "Night Ops",
        "Night Riot",
        "Oil Change",
        "Osiris",
        "Panther",
        "Photic Zone",
        "Polished Malachite",
        "Pyre",
        "Retribution",
        "Rose Nacre",
        "Royal Consorts",
        "Runic",
        "Rust Coat",
        "Sand Dashed",
        "Seabird",
        "Shred",
        "Space Cat",
        "Stained",
        "Sweet Little Angels",
        "Switch Board",
        "Tread",
        "Twin Turbo",
        "Urban Dashed",
        "Urban Shock",
        "Ventilators",
        "Water Sigil"
    ],
    "P90": [
    "Abstract",
    "Ancient Earth",
    "Ash Wood",
    "Asiimov",
    "Astral Jörmungandr",
    "Baroque Orange",
    "Blind Spot",
    "Bloomstick",
    "Bullet Rain",
    "Capillary",
    "Chopper",
    "Cocoa Rampage",
    "Cold Blooded",
    "Corroded",
    "Desert Rat",
    "Desert Warfare",
    "Death by Kitty",
    "Death Grip",
    "Death's Head",
    "Dispatch",
    "Dry Season",
    "Drunka",
    "Dystopian",
    "Elite Build",
    "Emerald Dragon",
    "Facility Dark",
    "Facility Negative",
    "Fallout Warning",
    "Feather-Weight",
    "Freight",
    "Glacier Mesh",
    "Glitch",
    "Grim",
    "Grid",
    "Grotesque",
    "Imperial",
    "Jade",
    "Leather",
    "Massacre",
    "Memento",
    "Module",
    "Neoqueen",
    "Nostalgia",
    "Off World",
    "Onyx",
    "Pandora's Box",
    "Paperclip",
    "Parchment",
    "Pigment",
    "Plague",
    "Run and Hide",
    "Sand Spray",
    "ScaraB Rush",
    "Schematic",
    "Scorched",
    "Serenity",
    "Shallow Grave",
    "Shapewood",
    "Shipping Forecast",
    "Splash",
    "Stained",
    "Storm",
    "Sunset Lily",
    "Teardown",
    "Tiger Pit",
    "Timber",
    "Traction",
    "Trigon",
    "Verdant Growth",
    "Virus",
    "Wave Spray",
    "Whiteout",
    "Zirka"
],
"UMP-45": [
    "Arctic Wolf",
    "Blaze",
    "Bone Pile",
    "Briefing",
    "Caramel",
    "Carbon Fiber",
    "Clear Polymer",
    "Compound",
    "Crime Scene",
    "Day Lily",
    "Delusion",
    "Desert DDPAT",
    "DDPAT",
    "Exposure",
    "Facility Dark",
    "Fallout Warning",
    "Full Stop",
    "Gold Bismuth",
    "Grand Prix",
    "Gunsmoke",
    "Houndstooth",
    "Indigo",
    "Labyrinth",
    "Mechanism",
    "Metal Flowers",
    "Minotaur's Labyrinth",
    "Momentum",
    "Moonrise",
    "Motorized",
    "Mudder",
    "Oscillator",
    "Para Green",
    "Plastique",
    "Primal Saber",
    "Roadblock",
    "Riot",
    "Scaffold",
    "Scorched",
    "Timber",
    "Urban DDPAT",
    "Wild Child",
    "Zipper"
],
    #Ciężkie

    "MAG-7": [
    "Amnesia",
    "Bomb Squad",
    "Carbon Fiber",
    "Chainmail",
    "Cinquedea",
    "Cobalt Core",
    "Copper Coated",
    "Core Breach",
    "Counter Terrace",
    "Firestarter",
    "Foresight",
    "Hard Water",
    "Hazard",
    "Heat",
    "Heaven Guard",
    "Insomnia",
    "Irradiated Alert",
    "Justice",
    "Memento",
    "Metallic DDPAT",
    "Monster Call",
    "Navy Sheen",
    "Petroglyph",
    "Popdog",
    "Praetorian",
    "Prism Terrace",
    "Rust Coat",
    "Sand Dune",
    "Seabird",
    "Silver",
    "Sonar",
    "Stealth",
    "Storm",
    "Sub-Zero",
    "Swag-7",
    "Tracer",
    "Weapon Case"
],
"Nova": [
    "Antique",
    "Army Sheen",
    "Baroque Orange",
    "Blaze Orange",
    "Bloomstick",
    "Bratatat",
    "Caged Steel",
    "Candy Apple",
    "Clear Polymer",
    "Clover",
    "Compound",
    "Contrast Spray",
    "Crystal",
    "Exo",
    "Field-Tested",
    "Forest Leaves",
    "Ghost Camo",
    "Gila",
    "Graphite",
    "Green Apple",
    "Hyper Beast",
    "Interlock",
    "Koi",
    "Mandrel",
    "Modern Hunter",
    "Moon in Libra",
    "Plume",
    "Polar Mesh",
    "Predator",
    "Quick Sand",
    "Ranger",
    "Red Quartz",
    "Rising Skull",
    "Rust Coat",
    "Sand Dune",
    "Scumbria",
    "Sobek's Bite",
    "Storm",
    "Surface Hardened",
    "Tempest",
    "Terrace",
    "Toy Soldier",
    "Walnut",
    "Wild Six",
    "Windblown",
    "Wood Fired"
],
"Sawed-Off": [
    "Abrasion",
    "Analog Input",
    "Apocalypto",
    "Bamboo Shadow",
    "Black Sand",
    "Brake Light",
    "Clay Ambush",
    "Copper",
    "Devourer",
    "First Class",
    "Forest DDPAT",
    "Fubar",
    "Full Stop",
    "Highwayman",
    "Irradiated Alert",
    "Jungle Thicket",
    "Kiss♥Love",
    "Kraken",
    "Limelight",
    "Mosaico",
    "Morris",
    "Oil Green",
    "Orange DDPAT",
    "Origami",
    "Parched",
    "Plaid",
    "Pyre",
    "Rise",
    "Rust Coat",
    "Sage Spray",
    "Scumbria",
    "Serenity",
    "Snake Camo",
    "Spirit Board",
    "Spotter",
    "Sudden Impact",
    "The Kraken",
    "The Yorick",
    "Tiger Moth",
    "Wasteland Princess",
    "Wired",
    "Woodsman",
    "Yorick",
    "Zander",
    "Zenith"
],
"XM1014": [
    "Ancient Lore",
    "Banshee",
    "Black DDPAT",
    "Black Tie",
    "Blaze Orange",
    "Blue Spruce",
    "Blue Steel",
    "Bone Machine",
    "CaliCamo",
    "Chartreuse",
    "Elegant Vines",
    "Entombed",
    "Fallout Warning",
    "Frost Borre",
    "Grassland",
    "Heaven Guard",
    "Hieroglyph",
    "HoneySuckle",
    "Incinerator",
    "Jungle",
    "Jungle Dashed",
    "Jungle Thicket",
    "Macabre",
    "Oxide Blaze",
    "Pink DDPAT",
    "Plague",
    "Quicksilver",
    "Ready Player",
    "Red Leather",
    "Red Python",
    "Roll Cage",
    "Sand Dashed",
    "Sand Dune",
    "Scumbria",
    "Seasons",
    "Slipstream",
    "StatTrak",
    "Steel Delta",
    "Sunstreak",
    "Teclu Burner",
    "Tranquility",
    "Tribute",
    "Urban Perforated",
    "VariCamo",
    "VariCamo Blue",
    "Watchdog",
    "XOXO",
    "Zombie Offensive"
],
"M249": [
    "Arctic Frog",
    "Aztec",
    "Blizzard Marble",
    "Boreal Forest",
    "Breach",
    "Contrast Spray",
    "Deep Relief",
    "Digital Mesh",
    "Downtown",
    "Emerald Poison Dart",
    "Gator Mesh",
    "Ghostly",
    "Impact Drill",
    "Jungle",
    "Jungle DDPAT",
    "Magma",
    "Midnight Palm",
    "Nebula Crusader",
    "O.S.I.P.R.",
    "Predator",
    "Re-Entry",
    "Safari Mesh",
    "Sand Dashed",
    "Sand Dune",
    "Shipping Forecast",
    "Spectre",
    "Stalker",
    "Sub-Zero",
    "System Lock",
    "Tempest",
    "Temple",
    "Urban Dashed",
    "Warbird",
    "Wild Lily",
    "Winter Forest"
],
"Negev": [
    "Anodized Navy",
    "Army Sheen",
    "Boroque Sand",
    "Bratatat",
    "Bulkhead",
    "CaliCamo",
    "Cobalt Halftone",
    "Darude",
    "Desert-Strike",
    "dev_texture",
    "Drop Me",
    "Infrastructure",
    "Lionfish",
    "Loudmouth",
    "Mjölnir",
    "Man-o'-war",
    "Nuclear Waste",
    "Palm",
    "Phoenix Stencil",
    "Power Loader",
    "Prototype",
    "Rattler",
    "Sand Dune",
    "Scanner",
    "Supernova",
    "Terrain",
    "Turret",
    "Ultralight"
],

    # --- Skrzynki (pusta lista oznacza brak drugiego wyboru) ---
    "CS:GO Weapon Case": [],
    "Operation Bravo Case": [],
    "Operation Phoenix Weapon Case": [],
    "Operation Vanguard Weapon Case": [],
    "Operation Breakout Weapon Case": [],
    "Operation Wildfire Case": [],
    "Operation Hydra Case": [],
    "Chroma Case": [],
    "Chroma 2 Case": [],
    "Chroma 3 Case": [],
    "Falchion Case": [],
    "Shadow Case": [],
    "Revolver Case": [],
    "Gamma Case": [],
    "Gamma 2 Case": [],
    "Glove Case": [],
    "Spectrum Case": [],
    "Spectrum 2 Case": [],
    "Clutch Case": [],
    "Horizon Case": [],
    "Danger Zone Case": [],
    "Prisma Case": [],
    "Prisma 2 Case": [],
    "CS20 Case": [],
    "Shattered Web Case": [],
    "Fracture Case": [],
    "Operation Riptide Case": [],
    "Operation Broken Fang Case": [],
    "Snakebite Case": [],
    "Dreams & Nightmares Case": [],
    "Recoil Case": [],
    "Revolution Case": [],
    "Kilowatt Case": [],
}

# Kategoryzacja broni (ułatwia selekcję w GUI)
# Klucz: polska nazwa kategorii -> lista kluczy z SKIN_DATA
WEAPON_CATEGORIES = {
    "Karabiny": [
        "AK-47", "M4A4", "M4A1-S", "FAMAS", "Galil AR", "AUG",
        "G3SG1", "SCAR-20", "SG 553", "SSG 08", "AWP"
    ],
    "Pistolety": [
        "Desert Eagle", "USP-S", "Glock-18", "Five-SeveN", "Tec-9",
        "CZ75-Auto", "P2000", "Dual Berettas", "P250", "R8 Revolver"
    ],
    "SMG": [
        "MP9", "MAC-10", "MP5-SD", "PP-Bizon", "P90", "UMP-45"
    ],
    "Strzelby": [
        "MAG-7", "Nova", "Sawed-Off", "XM1014"
    ],
    "Ciężkie": [
        "M249", "Negev"
    ],
    "Skrzynki": [k for k in SKIN_DATA.keys() if k.endswith('Case')],
    "Noże": [
        # Placeholdery — brak dedykowanych wpisów noży w SKIN_DATA teraz.
        # Możesz dodać klucze typu 'Karambit', 'M9 Bayonet' z listami skinów.
    ]
}